jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'

server:
  port: 8088
#  error:
#    whitelabel:
#      enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal #change this to your database url
    password: kash1979 #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${PORTAL_MAIL_USERNAME:fake.user@gmail.com}
#    password: ${PORTAL_MAIL_PASSWORD:fake_password}
#    properties:
#      mail:
#        transport:
#          protocol: smtp
#        smtp:
#          auth: true
#          starttls:
#            enable: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#  server.port=8088
#  spring.datasource.url=jdbc:mysql://localhost:3306/
#  # Datasource Driver Name
#  spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#  # Datasource User
#  spring.datasource.username=root
#  # Datasource password
#  spring.datasource.password=kash1979
#  # JPA DB Platform
#  spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
#  # JPA Show SQL
#  spring.jpa.show-sql = true
#  # JPA Hibernate AUTO DDL (for changes on entities to be automatically made in DB)
#  spring.jpa.hibernate.ddl-auto = update
#
